In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("kc_house_data .csv")
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
df.drop(["id","date", "yr_built", "yr_renovated"], axis = 1, inplace = True)

df.head(2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,zipcode,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,98178,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,98125,47.7210,-122.319,1690,7639

In [4]:
a = df.columns

In [9]:
df.shape

(21597, 17)

In [7]:
def outlier(data):
    a = df.columns
    for i in range(len(a)):
        d=data[a[i]]
        outlier1=[]
        data_mean = np.mean(d)
        data_std = np.std(d)
        threshold = 3
        for j in d:
            zscore = (j - data_mean)/data_std
        
            if(np.abs(zscore)> threshold):
                outlier1.append(j)
        for m in outlier1:
            data = data[data[data.columns[i]] !=m]
    return data

In [8]:
outlier(df)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,zipcode,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,98178,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,98125,47.7210,-122.319,1690,7639
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,98028,47.7379,-122.233,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,98136,47.5208,-122.393,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,98074,47.6168,-122.045,1800,7503
6,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,98003,47.3097,-122.327,2238,6819
7,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,98198,47.4095,-122.315,1650,9711
8,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,98146,47.5123,-122.337,1780,8113
9,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,98038,47.3684,-122.031,2390,7570
11,468000.0,2,1.00,1160,6000,1.0,0,0,4,7,860,300,98115,47.6900,-122.292,1330,6000
12,310000.0,3,1.00,1430,19901,1.5,0,0,4,7,1430,0,98028,47.7558,-122.229,1780,12697
13,400000.0,3,1.75,1370,9680,1.0,0,0,4,7,1370,0,98074,47.6127,-122.045,1370,10208
14,530000.0,5,2.00,1810,4850,1.5,0,0,3,7,1810,0,98107,47.6700,-122.394,1360,4850
16,395000.0,3,2.00,1890,14040,2.0,0,0,3,7,1890,0,98019,47.7277,-121.962,1890,14018
17,485000.0,4,1.00,1600,4300,1.5,0,0,4,7,1600,0,98103,47.6648,-122.343,1610,4300
18,189000.0,2,1.00,1200,9850,1.0,0,0,4,7,1200,0,98002,47.3089,-122.210,1060,5095
19,230000.0,3,1.00,1250,9774,1.0,0,0,4,7,1250,0,98003,47.3343,-122.306,1280,8850
20,385000.0,4,1.75,1620,4980,1.0,0,0,4,7,860,760,98133,47.7025,-122.341,1400,4980
22,285000.0,5,2.50,2270,6300,2.0,0,0,3,8,2270,0,98092,47.3266,-122.169,2240,7005
23,252700.0,2,1.50,1070,9643,1.0,0,0,3,7,1070,0,98030,47.3533,-122.166,1220,8386
24,329000.0,3,2.25,2450,6500,2.0,0,0,4,8,2450,0,98030,47.3739,-122.172,2200,6865
25,233000.0,3,2.00,1710,4697,1.5,0,0,5,6,1710,0,98002,47.3048,-122.218,1030,4705
26,937000.0,3,1.75,2450,2691,2.0,0,0,3,8,1750,700,98119,47.6386,-122.360,1760,3573
27,667000.0,3,1.00,1400,1581,1.5,0,0,5,8,1400,0,98112,47.6221,-122.314,1860,3861
28,438000.0,3,1.75,1520,6380,1.0,0,0,3,7,790,730,98115,47.6950,-122.304,1520,6235
29,719000.0,4,2.50,2570,7173,2.0,0,0,3,8,2570,0,98052,47.7073,-122.110,2630,6026
30,580500.0,3,2.50,2320,3980,2.0,0,0,3,8,2320,0,98027,47.5391,-122.070,2580,3980
31,280000.0,2,1.50,1190,1265,3.0,0,0,3,7,1190,0,98133,47.7274,-122.357,1390,1756
32,687500.0,4,1.75,2330,5000,1.5,0,0,4,7,1510,820,98117,47.6823,-122.368,1460,5000
33,535000.0,3,1.00,1090,3000,1.5,0,0,4,8,1090,0,98117,47.6889,-122.375,1570,5080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21563,645000.0,3,3.25,1730,1229,2.0,0,2,3,9,1320,410,98119,47.6374,-122.369,1710,1686
21564,594866.0,3,3.00,2780,6000,2.0,0,0,3,9,2780,0,98065,47.5184,-121.886,2850,6000
21565,625000.0,3,3.00,2780,6000,2.0,0,0,3,9,2780,0,98065,47.5184,-121.886,2850,6000
21566,490000.0,3,2.25,1500,1290,2.0,0,0,3,8,1220,280,98117,47.6785,-122.375,1460,1375
21567,399950.0,2,1.00,710,1157,2.0,0,0,4,7,710,0,98102,47.6413,-122.329,1370,1173
21568,380000.0,3,2.50,1260,900,2.0,0,0,3,7,940,320,98116,47.5621,-122.384,1310,1415
21569,270000.0,3,2.50,1870,5000,2.0,0,0,3,7,1870,0,98042,47.3339,-122.055,2170,5399
21570,505000.0,2,2.50,1430,1201,3.0,0,0,3,8,1430,0,98107,47.6707,-122.381,1430,1249
21571,385000.0,3,2.50,1520,1488,3.0,0,0,3,8,1520,0,98125,47.7337,-122.309,1520,1497
21572,414500.0,2,1.50,1210,1278,2.0,0,0,3,8,1020,190,98117,47.6756,-122.375,1210,1118
21573,347500.0,3,2.50,2540,4760,2.0,0,0,3,8,2540,0,98038,47.3452,-122.022,2540,4571
21575,572000.0,4,2.75,2770,3852,2.0,0,0,3,8,2770,0,98178,47.5001,-122.232,1810,5641
21576,475000.0,3,2.25,1190,1200,3.0,0,0,3,8,1190,0,98103,47.6542,-122.346,1180,1224
21578,350000.0,4,2.75,2500,5995,2.0,0,0,3,8,2500,0,98042,47.3749,-122.107,2530,5988
21579,520000.0,2,2.25,1530,981,3.0,0,0,3,8,1480,50,98103,47.6533,-122.346,1530,1282
21580,679950.0,5,2.75,3600,9437,2.0,0,0,3,9,3600,0,98059,47.4822,-122.131,3550,9421
21581,1580000.0,4,3.25,3410,10125,2.0,0,0,3,10,3410,0,98040,47.5653,-122.223,2290,10125
21582,541800.0,4,2.50,3118,7866,2.0,0,2,3,9,3118,0,98001,47.2931,-122.264,2673,6500
21585,467000.0,3,2.50,1425,1179,3.0,0,0,3,8,1425,0,98125,47.6963,-122.318,1285,1253
21586,224000.0,3,1.75,1500,11968,1.0,0,0,3,6,1500,0,98010,47.3095,-122.002,1320,11303
21587,507250.0,3,2.50,2270,5536,2.0,0,0,3,8,2270,0,98065,47.5389,-121.881,2270,5731
21588,429000.0,3,2.00,1490,1126,3.0,0,0,3,8,1490,0,98144,47.5699,-122.288,1400,1230
21589,610685.0,4,2.50,2520,6023,2.0,0,0,3,9,2520,0,98056,47.5137,-122.167,2520,6023
21590,1010000.0,4,3.50,3510,7200,2.0,0,0,3,9,2600,910,98136,47.5537,-122.398,2050,6200
21591,475000.0,3,2.50,1310,1294,2.0,0,0,3,8,1180,130,98116,47.5773,-122.409,1330,1265
21592,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,98103,47.6993,-122.346,1530,1509
21593,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,98146,47.5107,-122.362,1830,7200
21594,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,98144,47.5944,-122.299,1020,2007
21595,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,98027,47.5345,-122.069,1410,1287
21596,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,98144,47.5941,-122.299,1020,1357

In [25]:
y = df.iloc[:,0]
x = df.iloc[:,1:18]

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .20, random_state = 0)

In [28]:
x_train.shape

(17277, 16)

In [29]:
y_train.shape

(17277,)

In [30]:
from sklearn.linear_model import LinearRegression
p = LinearRegression()

In [31]:
p.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
pre = p.predict(x_test)

In [33]:
pre

array([ 887498.17185953,  707980.52418153,  993968.70009438, ...,
        534004.33734289, 1026245.17181549,  162364.22279458])

In [37]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
rmse = np.sqrt(mean_squared_error(y_test,pre))

In [38]:
rmse

194589.94557326025

In [39]:
r2_score(y_test, pre)

0.6783379432938377

In [41]:
print('Intercept: \n', p.intercept_)
print('Coefficients: \n', p.coef_)

Intercept:
 -32475409.698074423
Coefficients:
 [-3.12160124e+04  2.54351175e+03  1.28942052e+02  1.31387834e-01
 -2.46178997e+04  5.49995437e+05  6.43082470e+04  5.08454411e+04
  7.85334203e+04  8.18414179e+01  4.71006339e+01 -4.32503806e+02
  6.86127066e+05 -3.41045516e+05  2.01788223e+01 -3.94441243e-01]

In [45]:
pre1 = p.predict([[3,1.00,1180,5650,1.0,0,0,3,7,1180,0,98178,47.5112,-122.257,1340,5650]])

In [46]:
pre1

array([216979.20321063])