In [1]:
import pandas as pd
data = pd.read_csv("kc_house_data .csv")
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [2]:
x = data["bedrooms"]

In [3]:
data.drop(["id","date", "yr_built", "yr_renovated"], axis = 1, inplace = True)

data.head(2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,zipcode,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,98178,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,98125,47.7210,-122.319,1690,7639

In [3]:
import numpy as np
quartile1,quartile3=np.percentile(x,[25,75])

In [4]:
y = quartile1
y

3.0

In [5]:
z = quartile3
z

4.0

In [7]:
lower_limit = y - (1.5*(z-y))
lower_limit

1.5

In [8]:
upper_limit = z + (1.5*(z-y))
upper_limit

5.5

In [16]:
x = data["bathrooms"]

In [19]:
def outlier(data):
    out = []

    q1,q3=np.percentile(data,[25,75])
    l = q1 - (1.5*(q3-q1))
    u = q3 + (1.5*(q3-q1))
    for i in data:
        if(i>=u) or (i<=l):
            out.append(i)
    return(out)
outlier(x)

[4.5,
 4.0,
 4.0,
 4.75,
 5.0,
 4.25,
 4.5,
 4.25,
 3.75,
 5.0,
 4.0,
 4.0,
 4.25,
 4.25,
 4.25,
 4.5,
 4.5,
 3.75,
 4.5,
 4.0,
 4.5,
 5.25,
 4.0,
 3.75,
 4.5,
 4.5,
 4.25,
 6.0,
 3.75,
 4.25,
 4.0,
 3.75,
 3.75,
 4.75,
 5.0,
 3.75,
 3.75,
 3.75,
 5.0,
 4.25,
 3.75,
 4.0,
 4.25,
 4.5,
 3.75,
 4.0,
 3.75,
 5.0,
 3.75,
 4.0,
 3.75,
 3.75,
 4.25,
 4.0,
 4.25,
 4.25,
 4.5,
 3.75,
 4.0,
 3.75,
 5.0,
 3.75,
 0.5,
 4.0,
 5.0,
 5.0,
 4.5,
 5.5,
 4.25,
 4.0,
 4.5,
 3.75,
 3.75,
 4.5,
 3.75,
 5.5,
 4.25,
 5.5,
 5.25,
 4.25,
 4.0,
 4.5,
 3.75,
 3.75,
 3.75,
 3.75,
 4.25,
 4.5,
 4.75,
 3.75,
 3.75,
 3.75,
 3.75,
 3.75,
 4.5,
 4.25,
 4.0,
 4.75,
 4.75,
 3.75,
 4.5,
 4.0,
 3.75,
 3.75,
 4.0,
 4.0,
 3.75,
 4.75,
 4.5,
 3.75,
 6.75,
 6.0,
 4.5,
 5.5,
 4.5,
 3.75,
 4.0,
 4.25,
 3.75,
 5.75,
 3.75,
 4.0,
 4.0,
 4.0,
 5.25,
 4.75,
 4.0,
 4.25,
 3.75,
 4.0,
 4.0,
 5.25,
 3.75,
 3.75,
 3.75,
 4.5,
 5.0,
 3.75,
 3.75,
 4.5,
 4.0,
 3.75,
 3.75,
 4.0,
 4.75,
 3.75,
 4.25,
 5.0,
 3.75,
 4.0,
 4.25,
 4.0,
 4.0,
 4.5,
 4.75,
 4.0,
 4.0,
 4.0,
 4.5,
 3.75,
 3.75,
 4.5,
 5.75,
 4.75,
 3.75,
 4.0,
 4.0,
 3.75,
 4.25,
 4.25,
 3.75,
 4.5,
 5.5,
 4.0,
 4.5,
 4.5,
 4.0,
 4.5,
 4.25,
 8.0,
 3.75,
 4.25,
 4.0,
 3.75,
 4.5,
 3.75,
 4.5,
 4.5,
 4.5,
 4.0,
 4.25,
 5.0,
 4.5,
 4.25,
 4.5,
 6.75,
 4.0,
 3.75,
 4.5,
 4.25,
 3.75,
 4.5,
 3.75,
 3.75,
 4.0,
 7.5,
 4.0,
 4.0,
 4.0,
 4.25,
 3.75,
 4.5,
 3.75,
 4.25,
 4.25,
 4.5,
 4.5,
 4.25,
 7.75,
 4.25,
 4.75,
 4.0,
 4.0,
 4.25,
 4.0,
 4.0,
 4.5,
 4.25,
 4.0,
 4.5,
 4.25,
 4.0,
 4.25,
 3.75,
 4.0,
 4.0,
 4.0,
 4.0,
 4.5,
 3.75,
 4.25,
 4.0,
 3.75,
 5.0,
 3.75,
 4.25,
 3.75,
 4.0,
 4.0,
 3.75,
 5.5,
 0.5,
 4.0,
 3.75,
 4.25,
 3.75,
 3.75,
 4.5,
 4.0,
 4.0,
 4.25,
 4.0,
 4.5,
 4.5,
 4.5,
 3.75,
 4.25,
 3.75,
 4.5,
 3.75,
 4.25,
 4.0,
 4.5,
 0.5,
 3.75,
 4.25,
 4.5,
 4.5,
 4.25,
 4.0,
 4.0,
 3.75,
 4.5,
 4.5,
 3.75,
 0.5,
 4.25,
 3.75,
 3.75,
 4.0,
 4.75,
 4.5,
 4.5,
 4.0,
 3.75,
 4.0,
 6.0,
 3.75,
 4.0,
 4.25,
 4.0,
 3.75,
 4.25,
 4.0,
 4.5,
 3.75,
 4.0,
 3.75,
 4.5,
 8.0,
 4.25,
 3.75,
 4.0,
 4.5,
 4.25,
 5.0,
 5.25,
 3.75,
 4.5,
 4.0,
 4.75,
 4.0,
 4.5,
 3.75,
 4.0,
 5.5,
 3.75,
 4.75,
 4.0,
 4.0,
 3.75,
 3.75,
 4.25,
 4.5,
 4.25,
 4.5,
 6.25,
 3.75,
 4.0,
 4.0,
 3.75,
 3.75,
 3.75,
 4.5,
 5.0,
 4.0,
 4.5,
 4.0,
 4.25,
 4.5,
 3.75,
 4.0,
 3.75,
 4.5,
 4.75,
 4.75,
 4.0,
 4.0,
 3.75,
 3.75,
 3.75,
 3.75,
 4.75,
 3.75,
 3.75,
 5.25,
 3.75,
 5.75,
 4.5,
 5.0,
 4.5,
 5.0,
 3.75,
 3.75,
 4.5,
 3.75,
 4.25,
 4.25,
 4.0,
 3.75,
 4.0,
 4.25,
 5.0,
 3.75,
 4.0,
 4.0,
 4.0,
 5.75,
 5.25,
 3.75,
 3.75,
 4.5,
 4.0,
 4.0,
 5.25,
 4.5,
 4.0,
 3.75,
 4.25,
 4.0,
 4.25,
 4.5,
 4.0,
 4.25,
 4.0,
 4.25,
 4.5,
 3.75,
 4.25,
 4.0,
 4.5,
 4.0,
 4.5,
 3.75,
 5.25,
 4.0,
 3.75,
 3.75,
 4.0,
 3.75,
 4.5,
 4.5,
 3.75,
 5.25,
 6.25,
 4.0,
 4.75,
 4.75,
 5.0,
 5.25,
 4.5,
 4.0,
 3.75,
 4.0,
 4.0,
 4.5,
 3.75,
 4.0,
 3.75,
 5.5,
 4.25,
 4.0,
 4.25,
 3.75,
 6.0,
 4.25,
 3.75,
 4.25,
 4.25,
 4.5,
 4.5,
 4.0,
 4.0,
 3.75,
 5.0,
 3.75,
 3.75,
 3.75,
 4.25,
 3.75,
 4.0,
 3.75,
 4.5,
 4.0,
 4.0,
 4.25,
 4.25,
 4.5,
 4.0,
 4.5,
 3.75,
 4.0,
 4.5,
 4.0,
 4.5,
 4.0,
 4.25,
 4.75,
 3.75,
 4.75,
 4.0,
 4.0,
 3.75,
 4.5,
 5.25,
 4.5,
 4.5,
 3.75,
 3.75,
 3.75,
 4.0,
 3.75,
 3.75,
 5.5,
 4.5,
 4.25,
 4.5,
 4.5,
 4.25,
 4.0,
 4.0,
 4.0,
 4.25,
 3.75,
 4.25,
 4.25,
 3.75,
 3.75,
 4.0,
 5.5,
 3.75,
 4.0,
 3.75,
 3.75,
 4.5,
 4.5,
 4.25,
 4.0,
 6.5,
 4.5,
 3.75,
 3.75,
 4.0,
 4.75,
 3.75,
 3.75,
 4.0,
 4.0,
 3.75,
 5.25,
 4.25,
 4.5,
 5.0,
 4.0,
 4.0,
 6.0,
 5.0,
 4.0,
 4.0,
 4.5,
 3.75,
 4.75,
 4.25,
 6.0,
 3.75,
 3.75,
 3.75,
 4.0,
 4.0,
 4.5,
 4.25,
 6.5,
 3.75,
 4.0,
 3.75,
 4.0,
 4.5,
 4.0,
 4.5,
 3.75,
 3.75]

In [68]:
p =data.columns

In [69]:
p

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'zipcode', 'lat', 'long', 'sqft_living15',
       'sqft_lot15'],
      dtype='object')

In [72]:
def outlier(df):
    for i in range (len(p)):
        a = data[p[i]]
        q1,q3=np.percentile(df,[25,75])
        l = q1 - (1.5*(q3-q1))
        u = q3 + (1.5*(q3-q1))
        for j in df:
            if(j>=u) or (j<=l):
                data = data[p[i] !=j]
        return(data)
outlier(a)

UnboundLocalError: local variable 'data' referenced before assignment

In [66]:
for i in range (len(a)):
    print(a[i])
    k=data[a[i]]
    p1,p2=np.percentile(k,[25,75])
    l=p1-1.5*(p2-p1)
    u=p2+1.5*(p2-p1)
    for j in k:
        if(j>=u) or (j<=l):
            data =  data[a[i] !=j]
    print(data)

5650

KeyError: 5650

In [ ]:
p = data.drop